=== TU-Berlin/Mumie/japs/tools/xsd/DbHelper.xsd
<?xml version="1.0" encoding="ASCII"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:dbh="http://www.mumie.net/xml-namespace/db-helper"
            targetNamespace="http://www.mumie.net/xml-namespace/db-helper"
            elementFormDefault="qualified">

  <xsd:annotation>
    <xsd:documentation xml:lang="en">
      Author: Tilman Rassy &lt;rassy@math.tu-berlin.de&gt;
      $Id: DbHelper.xsd,v 1.4 2007/11/23 13:00:42 rassy Exp $

      Schema definition for XML documents that control the auto-coding of
      db helper classes.
    </xsd:documentation>
  </xsd:annotation>

  <!--
    ================================================================================
    Simple types
    ================================================================================
  -->

  <xsd:simpleType name="YesOrNo">
    <xsd:annotation>
      <xsd:documentation xml:lang="en">
        A variant of the boolean type. Can only take the values "yes" or "no".
      </xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="yes"/>
      <xsd:enumeration value="no"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="MethodName">
    <xsd:annotation>
      <xsd:documentation xml:lang="en">
        An unqualified method name in the Java programming language. Must meet
        the convention that method names start with a lower case letter.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="[a-z][A-Za-z_]*"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="VariableName">
    <xsd:annotation>
      <xsd:documentation xml:lang="en">
        An unqualified variable name in the Java programming language. Must meet
        the convention that variable names start with a lower case letter.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="[a-z][A-Za-z0-9_]*"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="ShortClassName">
    <xsd:annotation>
      <xsd:documentation xml:lang="en">
        An unqualified class name in the Java programming language. Must meet
        the convention that class names start with an upper case letter. Names
        includiong a '$' character (i.e., inner class names) are not allowed.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="[A-Z][A-Za-z_]*"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="ClassName">
    <xsd:annotation>
      <xsd:documentation xml:lang="en">
        A (qualified or unqualified) class name in the Java programming language.
        Must meet the convention that unqualified class names start with an upper
        case letter. Names includiong a '$' character (i.e., inner class names) are
        not allowed.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="([a-z_]+\.)*[A-Z][A-Za-z_]*"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="TypeName">
    <xsd:annotation>
      <xsd:documentation xml:lang="en">
        A type name in the Java programming language. May be a primitive type name
        or a class name, optionally followed by "[]" to indicate an array. See the
        "ClassName" type for the restriction on Java class names.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:string">
      <xsd:pattern
        value="(boolean|char|byte|short|int|long|float|double|void|([a-z_]+\.)*[A-Z][A-Za-z_]*)(\[\])?"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="AccessModifier">
    <xsd:annotation>
      <xsd:documentation xml:lang="en">
        An access modifier in the Java programming language. May be "public",
        "protected", or "private". 
      </xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="public"/>
      <xsd:enumeration value="protected"/>
      <xsd:enumeration value="private"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="Hint">
    <xsd:annotation>
      <xsd:documentation xml:lang="en">
        Hint for the autocoding process how a variable value should occur in
        a log message. Possible values and their meanings: "Identifyable" -
        an object implementing the Identifyable interface, "time" - a long
        value representing a time (milliseconds since midnight 1970), "array"
        - an array.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="Identifyable"/>
      <xsd:enumeration value="time"/>
      <xsd:enumeration value="array"/>
    </xsd:restriction>
  </xsd:simpleType>

  <!--
    ================================================================================
    Complex types
    ================================================================================
  -->

  <xsd:complexType name="DbHelper">
    <xsd:annotation>
      <xsd:documentation xml:lang="en">
        The root element.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:sequence>
      <xsd:element name="method" type="dbh:Method" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="Method">
    <xsd:annotation>
      <xsd:documentation xml:lang="en">
        Describes a method.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:sequence>
      <xsd:element name="params" type="dbh:Params" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="throws" type="dbh:Throws" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="doc" type="dbh:Doc" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="body" type="dbh:Body" minOccurs="0" maxOccurs="1"/>
    </xsd:sequence>
    <xsd:attribute name="name" type="dbh:MethodName" use="required"/>
    <xsd:attribute name="returnType" type="dbh:TypeName" use="optional"/>
    <xsd:attribute name="access" type="dbh:AccessModifier" use="optional"/>
    <xsd:attribute name="static" type="dbh:YesOrNo" use="optional"/>
    <xsd:attribute name="final" type="dbh:YesOrNo" use="optional"/>
    <xsd:attribute name="target" type="dbh:ShortClassName" use="optional"/>
    <xsd:attribute name="logging" type="dbh:YesOrNo" use="optional"/>
    <xsd:attribute name="toInterface" type="dbh:YesOrNo" use="optional"/>
  </xsd:complexType>

  <xsd:complexType name="Params">
    <xsd:annotation>
      <xsd:documentation xml:lang="en">
        Specifies the parameters (arguments) of a method.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:sequence>
      <xsd:element name="param" type="dbh:Param" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="Param">
    <xsd:annotation>
      <xsd:documentation xml:lang="en">
        Specifies a single parameter (argument) of a method.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:attribute name="name" type="dbh:VariableName" use="required"/>
    <xsd:attribute name="type" type="dbh:TypeName" use="required"/>
    <xsd:attribute name="hint" type="dbh:Hint" use="optional"/>
    <xsd:attribute name="log" type="dbh:YesOrNo" use="optional"/>
  </xsd:complexType>

  <xsd:complexType name="Throws">
    <xsd:annotation>
      <xsd:documentation xml:lang="en">
        Specifies the Throwables a method may throw.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:sequence>
      <xsd:element name="throwable" type="dbh:Throwable" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="Throwable">
    <xsd:annotation>
      <xsd:documentation xml:lang="en">
        Specifies a single Throwable a method may throw.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:attribute name="name" type="dbh:ClassName" use="required"/>
    <xsd:attribute name="doc" type="xsd:string" use="optional"/>
  </xsd:complexType>

  <xsd:complexType name="Doc" mixed="true">
    <xsd:annotation>
      <xsd:documentation xml:lang="en">
        Contains the API documentation of a method.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:sequence>
      <xsd:any namespace="http://www.mumie.net/xml-namespace/html-in-javadoc"
               minOccurs="0"
               maxOccurs="unbounded"
               processContents="skip"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="Body" mixed="true">
    <xsd:annotation>
      <xsd:documentation xml:lang="en">
        Contains the body of a method.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:sequence>
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element name="sqlComposer" type="dbh:SqlComposer"/>
        <xsd:element name="log" type="dbh:Log"/>
      </xsd:choice>
      <xsd:choice minOccurs="0" maxOccurs="1">
        <xsd:element name="returnResultSet" type="dbh:ReturnResultSet"/>
        <xsd:element name="executeInsertAndReturnId" type="dbh:ExecuteInsertAndReturnId"/>
        <xsd:element name="pgExecuteInsertAndReturnId" type="dbh:PgExecuteInsertAndReturnId"/>
        <xsd:element name="executeUpdate" type="dbh:ExecuteUpdate"/>
      </xsd:choice>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="SqlComposer">
    <xsd:annotation>
      <xsd:documentation xml:lang="en">
        Contains a piece of SQL pseudo-code. The latter is converted to Java code
        at build-time. The (compiled) Java code then creates real SQL code at
        runtime.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:simpleContent>
      <xsd:extension base="xsd:string">
        <xsd:attribute name="clear" type="dbh:YesOrNo" use="optional"/>
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>

  <xsd:complexType name="Log">
    <xsd:annotation>
      <xsd:documentation xml:lang="en">
        Specifies a log message.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:simpleContent>
      <xsd:extension base="xsd:string">
        <xsd:attribute name="number" type="xsd:string" use="optional"/>
        <xsd:attribute name="printParams" type="dbh:YesOrNo" use="optional"/>
        <xsd:attribute name="linebreak" type="dbh:YesOrNo" use="optional"/>
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>

  <xsd:complexType name="ReturnResultSet">
    <xsd:annotation>
      <xsd:documentation xml:lang="en">
        Represents a Java code fragment that creates the SQL code as a string,
        prints a log message if desired, executes the query, and returns the
        ResultSet.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:attribute name="withLogNumber" type="xsd:string" use="optional"/>
  </xsd:complexType>

  <xsd:complexType name="ExecuteInsertAndReturnId">
    <xsd:annotation>
      <xsd:documentation xml:lang="en">
        Represents a Java code fragment that executes an INSERT query and returns
        the autogenerated id. If disered, log messages are created.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:attribute name="withLogNumber" type="xsd:string" use="optional"/>
  </xsd:complexType>

  <xsd:complexType name="PgExecuteInsertAndReturnId">
    <xsd:annotation>
      <xsd:documentation xml:lang="en">
        Represents a PostgreSQL-specific Java code fragment that executes an INSERT query
        and returns the autogenerated id. If disered, log messages are created.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:attribute name="withLogNumber" type="xsd:string" use="optional"/>
    <xsd:attribute name="table" type="xsd:string" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="ExecuteUpdate">
    <xsd:annotation>
      <xsd:documentation xml:lang="en">
        Represents a Java code fragment that executes an UPTATE query. If disered,
        a log messages is created.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:attribute name="withLogNumber" type="xsd:string" use="optional"/>
  </xsd:complexType>

  <!--
    ================================================================================
    Root element
    ================================================================================
  -->

  <xsd:element name="DbHelper" type="dbh:DbHelper"/>

</xsd:schema>

=== TU-Berlin/Mumie/mmsrv/src/java/net/mumie/srv/db/DbHelper.xml
<?xml version="1.0" encoding="ASCII"?>


<!--
  The MIT License (MIT)
  
  Copyright (c) 2010 Technische Universitaet Berlin
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
-->

<!--
  <dbh:method name="">
    <dbh:params>
      <dbh:param type="" name=""/>
      <dbh:param type="" name=""/>
      <dbh:param type="" name=""/>
      <dbh:param type="" name=""/>
    </dbh:params>
    <dbh:throws>
      <dbh:throwable name="SQLException"/>
    </dbh:throws>
    <dbh:doc>
    </dbh:doc>
    <dbh:body>
      <dbh:sqlComposer>
      </dbh:sqlComposer>
      <dbh:returnResultSet/>
    </dbh:body>
  </dbh:method>
-->

<dbh:DbHelper xmlns:dbh="http://www.mumie.net/xml-namespace/db-helper"
              xmlns:h="http://www.mumie.net/xml-namespace/html-in-javadoc"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://www.mumie.net/xml-namespace/db-helper DbHelper.xsd">

<!-- ================================================================================ -->
<!-- h1: Executing custom SQL                                                         -->
<!-- ================================================================================ -->

  <dbh:method name="query">
    <dbh:params>
      <dbh:param type="String" name="query"/>
      <dbh:param type="boolean" name="scrollable"/>
    </dbh:params>
    <dbh:throws>
      <dbh:throwable name="SQLException"/>
    </dbh:throws>
    <dbh:doc>
      * Executes the specified query and returns the corresponding result set.
    </dbh:doc>
    <dbh:body>
      <dbh:log printParams="yes">"Started"</dbh:log>
      int type = (scrollable ? ResultSet.TYPE_SCROLL_INSENSITIVE : ResultSet.TYPE_FORWARD_ONLY);
      Statement statement = this.connection.createStatement(type, ResultSet.CONCUR_READ_ONLY);
      ResultSet resultSet = statement.executeQuery(query);
      <dbh:log>"Done"</dbh:log>
      return resultSet;
    </dbh:body>
  </dbh:method>
  
<!-- ================================================================================ -->
<!-- h1: Querying entity data                                                         -->
<!-- ================================================================================ -->

<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<!-- h2: Non-binary data                                                              -->
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->

  <dbh:method name="queryEntity">
    <dbh:params>
      <dbh:param type="int" name="type"/>
      <dbh:param type="int" name="id"/>
      <dbh:param type="String..." name="columns" hint="array"/>
    </dbh:params>
    <dbh:throws>
      <dbh:throwable name="SQLException"/>
    </dbh:throws>
    <dbh:doc>
      * Queries the specified columns of the entity with the specified type and id.
    </dbh:doc>
    <dbh:body>
      <dbh:sqlComposer>
        SELECT
        columns(this.filterColumns(columns))
        FROM
        table(DbTable.ofEntityTypeForRead(type))
        WHERE
        column(DbColumn.ID) = value(id)
      </dbh:sqlComposer>
      <dbh:returnResultSet/>
    </dbh:body>
  </dbh:method>

  <dbh:method name="queryEntityDatumAsTimestamp" returnType="Timestamp">
    <dbh:params>
      <dbh:param type="int" name="type"/>
      <dbh:param type="int" name="id"/>
      <dbh:param type="String" name="column"/>
    </dbh:params>
    <dbh:throws>
      <dbh:throwable name="SQLException"/>
    </dbh:throws>
    <dbh:doc>
      * Returns the specified column of the entity with the specified type and id
      * as a {@link Timestamp Timestamp} object.
    </dbh:doc>
    <dbh:body>
      <dbh:log printParams="yes">"Started"</dbh:log>
      ResultSet resultSet = this.queryEntity(type, id, column);
      if ( ! resultSet.next() )
        throw new SQLException
          (METHOD_NAME + ": Cannot find entity with type " + type + " and id " + id);
      Timestamp value = resultSet.getTimestamp(column);
      <dbh:log>"Done. value = " + LogUtil.dateToString(value)</dbh:log>
      return value;
    </dbh:body>
  </dbh:method>

  <dbh:method name="queryEntityDatumAsString" returnType="String">
    <dbh:params>
      <dbh:param type="int" name="type"/>
      <dbh:param type="int" name="id"/>
      <dbh:param type="String" name="column"/>
    </dbh:params>
    <dbh:throws>
      <dbh:throwable name="SQLException"/>
    </dbh:throws>
    <dbh:doc>
      * Returns the specified column of the entity with the specified type and id
      * as a string.
    </dbh:doc>
    <dbh:body>
      <dbh:log printParams="yes">"Started"</dbh:log>
      ResultSet resultSet = this.queryEntity(type, id, column);
      if ( ! resultSet.next() )
        throw new SQLException
          (METHOD_NAME + ": Cannot find entity with type " + type + " and id " + id);
      String value = resultSet.getString(column);
      <dbh:log>"Done. value = " + value</dbh:log>
      return value;
    </dbh:body>
  </dbh:method>
  
  <dbh:method name="queryEntityDatumAsInt" returnType="int">
    <dbh:params>
      <dbh:param type="int" name="type"/>
      <dbh:param type="int" name="id"/>
      <dbh:param type="String" name="column"/>
    </dbh:params>
    <dbh:throws>
      <dbh:throwable name="SQLException"/>
    </dbh:throws>
    <dbh:doc>
      * Returns the specified column of the entity with the specified type and id
      * as an <h:code>int</h:code> number.
    </dbh:doc>
    <dbh:body>
      <dbh:log printParams="yes">"Started"</dbh:log>
      ResultSet resultSet = this.queryEntity(type, id, column);
      if ( ! resultSet.next() )
        throw new SQLException
          (METHOD_NAME + ": Cannot find entity with type " + type + " and id " + id);
      int value = resultSet.getInt(column);
      <dbh:log>"Done. value = " + value</dbh:log>
      return value;
    </dbh:body>
  </dbh:method>
  
  <dbh:method name="queryEntityDatumAsLong" returnType="long">
    <dbh:params>
      <dbh:param type="int" name="type"/>
      <dbh:param type="int" name="id"/>
      <dbh:param type="String" name="column"/>
    </dbh:params>
    <dbh:throws>
      <dbh:throwable name="SQLException"/>
    </dbh:throws>
    <dbh:doc>
      * Returns the specified column of the entity with the specified type and id
      * as an <h:code>long</h:code> number.
    </dbh:doc>
    <dbh:body>
      <dbh:log printParams="yes">"Started"</dbh:log>
      ResultSet resultSet = this.queryEntity(type, id, column);
      if ( ! resultSet.next() )
        throw new SQLException
          (METHOD_NAME + ": Cannot find entity with type " + type + " and id " + id);
      long value = resultSet.getLong(column);
      <dbh:log>"Done. value = " + value</dbh:log>
      return value;
    </dbh:body>
  </dbh:method>
  
  <dbh:method name="queryEntityDatumAsBoolean" returnType="boolean">
    <dbh:params>
      <dbh:param type="int" name="type"/>
      <dbh:param type="int" name="id"/>
      <dbh:param type="String" name="column"/>
    </dbh:params>
    <dbh:throws>
      <dbh:throwable name="SQLException"/>
    </dbh:throws>
    <dbh:doc>
      * Returns the specified column of the entity with the specified type and id
      * as a boolean value.
    </dbh:doc>
    <dbh:body>
      <dbh:log printParams="yes">"Started"</dbh:log>
      ResultSet resultSet = this.queryEntity(type, id, column);
      if ( ! resultSet.next() )
        throw new SQLException
          (METHOD_NAME + ": Cannot find entity with type " + type + " and id " + id);
      boolean value = resultSet.getBoolean(column);
      <dbh:log>"Done. value = " + value</dbh:log>
      return value;
    </dbh:body>
  </dbh:method>

<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<!-- h2: By path                                                                  -->
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->

  <dbh:method name="queryEntityByPath" target="PostgreSQLDbHelper">
    <dbh:params>
      <dbh:param type="int" name="type"/>
      <dbh:param type="String" name="path"/>
      <dbh:param type="String[]" name="columns"/>
      <dbh:param type="boolean" name="onlyLatest"/>
    </dbh:params>
    <dbh:throws>
      <dbh:throwable name="SQLException"/>
    </dbh:throws>
    <dbh:doc>
      * Returns the specified columns for the entities with the specified type and path.
      * If <h:code>onlyLatest</h:code> is <h:code>true</h:code>, only latest versions of
      * the entities are consdidered.
    </dbh:doc>
    <dbh:body>
      this.pathTokenizer.tokenize(path);
      String sectionPath = this.pathTokenizer.getSectionPath();
      String pureName = this.pathTokenizer.getPureName();
      <dbh:sqlComposer>
        SELECT
        columns(this.filterColumns(columns))
        FROM
        table(DbTable.ofEntityTypeForRead(type, onlyLatest))
        WHERE
